kind: Job
apiVersion: batch/v1
metadata:
  name: anchor-deploy
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: anchor-deploy
          image: anchor-deploy
          command:
            # TODO: Test this
             - /bin/sh
             - -c
             - 'echo "test"'
             # - 'solana program deploy -u http://solana-devnet:8889 -k solana/keys/solana-devnet.json'
---

