kind: Job
apiVersion: batch/v1
metadata:
  name: anchor-deploy
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: anchor-deploy
          image: anchor-deploy
          command:
            - /root/.local/share/solana/install/active_release/bin/solana
            - program 
            - deploy 
            - /opt/solana/deps/example_native_token_transfers.so'
            - -u 
            - http://solana-devnet:8899 
            - -k 
            - /opt/solana/deps/solana-devnet.json 
